#!/bin/bash
set -e

if [ "$1" = "configure" ]; then
    # Reload systemd manager configuration
    systemctl daemon-reload
    
    # Enable and start the service
    systemctl enable openbackd.service
    systemctl restart openbackd.service || true
fi

exit 0
